FROM    docker.io/redhat/ubi9
ADD     --keep-git-dir https://github.com/pdevops87/roboshop-dockerfile-v1.git  /
CMD ["sleep","100"]


# we are adding git repo raw data into a container, to know explicitly .git files add "--keep-git-dir"