FROM          docker.io/redhat/ubi9
ARG           username
ARG           buildno
CMD           ["sleep","100"]


# here adding two arguments it is just like vars
# docker build --build-arg username=aadi --build-arg=buildno=122 -t arg:1.0 .
