FROM           docker.io/redhat/ubi9
CMD            ["echo","Hello World"]

# default run /bin/bash -c to execute echo inside a container and displays Hello World

#  we can override the content also through cli
# docker run myimage  Hello Universe then o/p override as Hello Universe
