FROM             docker.io/redhat/ubi9
COPY             run.sh /run.sh
ENTRYPOINT ["echo"]
CMD ["Hello World"]


# this is shell form "ENTRYPOINT echo Hello World"
# here we have to specify default command to execute and display Hello World
