FROM     docker.io/redhat/ubi9
CMD      ["echo" , "Hello World"]



# CMD      ["echo" , "Hello World"] this is executable form and pass directly to the shell without calling shell command
# CMD echo Hello World


# FROM     docker.io/redhat/ubi9
# CMD      echo Hello World


#  it will call default shell command /bin/bash -c here -c is a command
#  /bin/sh -c "echo Hello World", where -c tells the shell to execute the string as a command


