FROM                docker.io/redhat/ubi9
RUN                 mkdir -p /app
RUN                 curl -L -o /tmp/frontend.zip  https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
CMD ["sleep","100"]
