FROM                        docker.io/redhat/ubi9
ARG                         name
ARG                         training
ENV                         username=${name} training=${training}
CMD                         ["sleep","100"]